# Harmono Jekyll theme general configurations

# Site URL
# url: https://kuoe0.github.io
url: "http://www.cabbage.space"
# Base URL (https://kuoe0.github.io{/baseurl})
baseurl: ""

# Harmono theme configuration. Please change accordingly.
harmono:
  name: I'm cabbage
  # Little description about your site
  description: I am an iOS developer, working in ezbuy company.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  # Google Analytics key, leave blank to ignore
  google_analytics_key: 
  # Profile links, leave blank to ignore
  social:
    email:    zhangpeng@ezbuy.com
    # linkedin: linkedin_name
    github:   570262616
    twitter:  大白菜cabbage
    facebook: 大白菜cabbage
    # gplus:    gplus_name

  page_list:
    - About
    - Archive
    - FAQ

  # Toggle disclaimer in footer
  show_disclaimer: false

  # Toggle comment system
  comment: false
  # Comment system provider
  duoshuo_username: cabbages

  disqus:
    short_name: 

# Conversion / Build settings
markdown: kramdown
# kramdown:
#   input: GFM
#   # syntax_highlighter: rouge
#   # syntax_highlighter_opts:
#   #   # Rouge Options › https://github.com/jneen/rouge#full-options
#   #   default_lang: swift
#   #   css_class: 'highlight'
#   #   #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#   #   span:
#   #     line_numbers: false
#   #   block:
#   #     line_numbers: true
#   #     start_line: 1
#   #   wrap: true

# # source code highlight
highlighter: rouge # must be rouge if using Jekyll 3.0+
highlight_theme: swift

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
